{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubehub.fullname" . }}
  labels:
    {{- include "kubehub.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.ingress.redirectHttps }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.redirectHttps }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "kubehub.fullname" . }}-https-redirect@kubernetescrd
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.apiPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "kubehub.api.fullname" . }}
                port:
                  number: 8000
          - path: {{ .Values.ingress.webPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "kubehub.web.fullname" . }}
                port:
                  number: 3000
{{- end }}
