apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubehub.web.fullname" . }}
  labels:
    {{- include "kubehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "kubehub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
